### ISSUE TITLE
! LaTeX Error: File `abnt.cls' not found.

### ISSUE THREAD

**Issue by dansku** [mateusduboli/ufsc-thesis-latex#11]
Estou tentando compilar o código de exemplo, estou com o MacTex2013 instalado com o abntex2, porém quando tento compilar ele da esse erro pedindo o abnt.cls.

Aqui vai o log de compilação:

/usr/texbin/pdflatex -file-line-error -interaction=nonstopmode -synctex=1 -output-directory=/Users/admin/Dropbox/UFSC/TCC/TCC_Daniel_Spillere_Andrade/Amigos/Mateus/ufsc-thesis-latex/template-antigo/.texpadtmp exemplo.tex
This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013)
 restricted \write18 enabled.
entering extended mode
(./exemplo.tex
LaTeX2e <2011/06/27>
Babel <3.9f> and hyphenation patterns for 78 languages loaded.
(./ufscThesis.cls
Document Class: ufscThesis 

! LaTeX Error: File `abnt.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name: 
./ufscThesis.cls:31: Emergency stop.
<read *> 

l.31 ^^M

./ufscThesis.cls:31:  ==> Fatal error occurred, no output PDF file produced!
Transcript written on /Users/admin/Dropbox/UFSC/TCC/TCC_Daniel_Spillere_Andrade
/Amigos/Mateus/ufsc-thesis-latex/template-antigo/.texpadtmp/exemplo.log.

/usr/texbin/pdflatex -file-line-error -interaction=nonstopmode -synctex=1 -output-directory=/Users/admin/Dropbox/UFSC/TCC/TCC_Daniel_Spillere_Andrade/Amigos/Mateus/ufsc-thesis-latex/template-antigo/.texpadtmp exemplo.tex
This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013)
 restricted \write18 enabled.
entering extended mode
(./exemplo.tex
LaTeX2e <2011/06/27>
Babel <3.9f> and hyphenation patterns for 78 languages loaded.
(./ufscThesis.cls
Document Class: ufscThesis 

! LaTeX Error: File `abnt.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name: 
./ufscThesis.cls:31: Emergency stop.
<read *> 

l.31 ^^M

./ufscThesis.cls:31:  ==> Fatal error occurred, no output PDF file produced!
Transcript written on /Users/admin/Dropbox/UFSC/TCC/TCC_Daniel_Spillere_Andrade
/Amigos/Mateus/ufsc-thesis-latex/template-antigo/.texpadtmp/exemplo.log.

Obrigado!

**Comment by charlesdccti** [comment]
como resolveu?
