### ISSUE TITLE
Alterar folha de rosto para o modelo da UFSC

### ISSUE THREAD

**Issue by mateusduboli** [mateusduboli/ufsc-thesis-latex#8]
Alterar folha de rosto para:
* Imprimir subtítulo
* Retirar o negrito do nome do autor.

**Comment by dudektria** [comment]
Eu fiz meu TCC baseado na sua classe e criei uma folha de rosto de acordo com o modelo fornecido pelo Departamento de Química. Em que pé tá esse issue? Eu posso pegar parte do meu trabalho e contribuir. Aonde há um modelo para teses na internet?

**Comment by mateusduboli** [comment]
Está de pé sim!
Sobre o modelo não entendi, que modelo você gostaria?

**Comment by dudektria** [comment]
Um para folha de rosto de teses da UFSC.
